<!DOCTYPE html>

<html>
<head>
	<link rel="stylesheet" type="text/css" href="style.css">
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
	<div id="loadingScreen">
		<img src="res/loading.gif"><br>
		<p>Loading...</p>
		<p id="progress">5%</p>
	</div>
	<div id="navbar">
		<a href="index.php">
		<div class="icon"><img src="res/buildings.png">
			<div class="tagline">Home</div>
		</div>
		</a>
		<a href="about.html">
		<div class="icon"><img src="res/sign.png">
			<div class="tagline">Info</div>
		</div>
		</a>
		<a href="test.php">
		<div class="icon"><img src="res/science.png">
			<div class="tagline">Testing</div>
		</div>
		</a>
		<a href="sources.html">
		<div class="icon"><img src="res/library.png">
			<div class="tagline">Sources</div>
		</div>
		</a>
	</div>

	<div id="textContent">

		<h1>Testing Center</h1>
		<p class="info">
			This is the testing center. Here, you can help make stochatta better by answering a few questions.
		</p>
		<p class="info">
			Below are some selections from famous philosophers, as well as snippets generated by Stochatta. Simply identify which ones are the philosopher (green) and which ones are Stochatta (red), and find out how well you did afterword!
		</p>
		<p class="info">
			Because it takes about 1 minute for stochatta to generate sentences, each quote, human and machine, has been generated ahead of time. Thus, if you see duplicate quotes, this does not indicate whether or not they are human. It simply means that the testing center has run into the same quotes in the database.
		</p>
		<h3>#1</h3>
		<div class="selection" id="0"><div class="pre-show" id="quote0"></div></div>
		<div id="buttonarea" parent="0">
			<div class="button real" onclick="setChoice(this, 'rgba(46,204,113,0.3)', 0)">
				Man
			</div>
			<div class="button machine" onclick="setChoice(this, 'rgba(231,76,70,0.3)', 1)">
				Machine
			</div>
		</div>
		<h3>#2</h3>
		<div class="selection" id="1"><div class="pre-show" id="quote1"></div></div>
		<div id="buttonarea" parent="1">
			<div class="button real" onclick="setChoice(this, 'rgba(46,204,113,0.3)', 0)">
				Man
			</div>
			<div class="button machine" onclick="setChoice(this, 'rgba(231,76,70,0.3)', 1)">
				Machine
			</div>
		</div>
		<h3>#3</h3>
		<div class="selection" id="2"><div class="pre-show" id="quote2"></div></div>
		<div id="buttonarea" parent="2">
			<div class="button real" onclick="setChoice(this, 'rgba(46,204,113,0.3)', 0)">
				Man
			</div>
			<div class="button machine" onclick="setChoice(this, 'rgba(231,76,70,0.3)', 1)">
				Machine
			</div>
		</div>
		<h3>#4</h3>
		<div class="selection" id="3"><div class="pre-show" id="quote3"></div></div>
		<div id="buttonarea" parent="3">
			<div class="button real" onclick="setChoice(this, 'rgba(46,204,113,0.3)', 0)">
				Man
			</div>
			<div class="button machine" onclick="setChoice(this, 'rgba(231,76,70,0.3)', 1)">
				Machine
			</div>
		</div>
		<h3>#5</h3>
		<div class="selection" id="4"><div class="pre-show" id="quote4"></div></div>
		<div id="buttonarea" parent="4">
			<div class="button real" onclick="setChoice(this, 'rgba(46,204,113,0.3)', 0)">
				Man
			</div>
			<div class="button machine" onclick="setChoice(this, 'rgba(231,76,70,0.3)', 1)">
				Machine
			</div>
		</div>
		<h3>#6</h3>
		<div class="selection" id="5"><div class="pre-show" id="quote5"></div></div>
		<div id="buttonarea" parent="5">
			<div class="button real" onclick="setChoice(this, 'rgba(46,204,113,0.3)', 0)">
				Man
			</div>
			<div class="button machine" onclick="setChoice(this, 'rgba(231,76,70,0.3)', 1)">
				Machine
			</div>
		</div>
		<h3>#7</h3>
		<div class="selection" id="6"><div class="pre-show" id="quote6"></div></div>
		<div id="buttonarea" parent="6">
			<div class="button real" onclick="setChoice(this, 'rgba(46,204,113,0.3)', 0)">
				Man
			</div>
			<div class="button machine" onclick="setChoice(this, 'rgba(231,76,70,0.3)', 1)">
				Machine
			</div>
		</div>
		<h3>#8</h3>
		<div class="selection" id="7"><div class="pre-show" id="quote7"></div></div>
		<div id="buttonarea" parent="7">
			<div class="button real" onclick="setChoice(this, 'rgba(46,204,113,0.3)', 0)">
				Man
			</div>
			<div class="button machine" onclick="setChoice(this, 'rgba(231,76,70,0.3)', 1)">
				Machine
			</div>
		</div>
		<h3>#9</h3>
		<div class="selection" id="8"><div class="pre-show" id="quote8"></div></div>
		<div id="buttonarea" parent="8">
			<div class="button real" onclick="setChoice(this, 'rgba(46,204,113,0.3)', 0)">
				Man
			</div>
			<div class="button machine" onclick="setChoice(this, 'rgba(231,76,70,0.3)', 1)">
				Machine
			</div>
		</div>
		<h3>#10</h3>
		<div class="selection" id="9"><div class="pre-show" id="quote9"></div></div>
		<div id="buttonarea" parent="9">
			<div class="button real" onclick="setChoice(this, 'rgba(46,204,113,0.3)', 0)">
				Man
			</div>
			<div class="button machine" onclick="setChoice(this, 'rgba(231,76,70,0.3)', 1)">
				Machine
			</div>
		</div>
		<div id="submit">

			<div class="button submit" onclick="submit()">
				Submit
			</div>


		</div>
		<div id="submitwarning">
		</div>
	</div>

	<script>

		var counted = 0;

		var quotes = new Array(10);
		var quotesbuffer = new Array();
		var humanQuotesBuffer = new Array();
		
		var fullyloaded = new Event('fullyloaded');
		var loaded = new Event('loaded');
		var humanloaded = new Event('humanloaded');

		var xhr = [];
		var humanxhr = [];

		generateSentences();

		function submit(){
			var accuracy = 0;

			for(var i = 0; i < 10; i++){
				if(!document.getElementById(i).hasAttribute("choice")){
					document.getElementById("submitwarning").innerHTML = "You must make a choice for all questions!";
					return 1;
				}
				else if(parseInt(document.getElementById(i).getAttribute("choice")) == parseInt(document.getElementById(i).getAttribute("answer"))){
					accuracy += 1;
				}
			}

			window.location="submit.php?results=" + accuracy;
		}

		function generateSentences(){

			var counter = 0;

			var machines = Math.floor(Math.random() * 7) + 2;
			
			var machinesLoaded = new CustomEvent("Machines Loaded", null);

			xhr = new Array(machines);

			for(var i = 0; i < machines; i++){
				var machineLocation = 0;
				do{
					machineLocation = Math.floor(Math.random() * 10);
				}while(quotes[machineLocation])
				quotes[machineLocation] = 1;	
				xhr[i] = new XMLHttpRequest();
				xhr[i].onreadystatechange = function(index){
					return function(){
						if(xhr[index].readyState == 4 && xhr[index].status == 200){
							counted++;
							quotesbuffer.push(xhr[index].responseText);
							console.log(xhr[index].responseText);
							document.dispatchEvent(loaded);
						}else{
							console.log(xhr[index].readyState + ", " + xhr[index].status);
						}
					}
				}(i);
				xhr[i].open('GET', 'testprefab.php', true);
				xhr[i].send();

			}

			humanxhr = new Array(10 - machines);
			for(var i = 0; i < quotes.length; i++){
				if(!quotes[i]){
					quotes[i] = 0;
					humanxhr[i] = new XMLHttpRequest();
					humanxhr[i].onreadystatechange = function(index){
						return function(){
							if(humanxhr[index].readyState == 4 && humanxhr[index].status == 200){
								humanQuotesBuffer.push(humanxhr[index].responseText);
								counted++;
								document.dispatchEvent(humanloaded);
							}
						}
					}(i);
					humanxhr[i].open("GET", "human.php", true);
					humanxhr[i].send();
				}
			}

			console.log(quotes);
		}
		document.addEventListener('loaded', function(){
			for(var i = 0; i < quotes.length; i++){
				if(quotes[i] == 1){
					document.getElementById(i).setAttribute("answer", "1");
					document.getElementById("quote" + i).innerHTML = "<i>[...] " + quotesbuffer.pop() + " [...]</i>";
					quotes[i] = -1;

					document.getElementById("progress").innerHTML = Math.floor(counted/9 * 100) + "%";

					if(counted == 9)
						document.dispatchEvent(fullyloaded);
					break;
				}
			}
			console.log(counted + " xhrs");
		});
		document.addEventListener('humanloaded', function(){
			for(var i = 0; i < quotes.length; i++){
				if(quotes[i] == 0){
					document.getElementById(i).setAttribute("answer", "0");
					document.getElementById("quote" + i).innerHTML = "<i>[...] " + humanQuotesBuffer.pop() + " [...]</i>";
					quotes[i] = -1;
					document.getElementById("progress").innerHTML = Math.floor(counted/9 * 100) + "%";

					if(counted == 9)
						document.dispatchEvent(fullyloaded);
					break;
				}
			}
		});
		document.addEventListener('fullyloaded', function(){
			for(var i = 0; i < 10; i++){
				document.getElementById("quote" + i).style.visibility = "visible";
				document.getElementById("quote" + i).style.height = "auto";
				document.getElementById("loadingScreen").style.visibility = "hidden";
				
			}
		});

		function setChoice(dom, color, choice){
			var ctx = dom.parentElement;
			var selection = document.getElementById(ctx.getAttribute("parent"));
			selection.style.background = color;
			selection.setAttribute("choice", choice);
			
		}

	</script>
</body>
